name: CI/CD WorkFlow

on:
  push:
    branches:
     - main
  workflow_dispatch:
jobs:
  build-test-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
     - name: Get Code
       uses: actions/checkout@v4
     - name: Node
       uses: actions/setup-node@v4.0.0
       with: 
         node-version: current
     - run: npm ci
     - run: npm run build
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v2
       with:
        path: './dist'
     - name: Deploy Site
       uses: actions/deploy-pages@v1.2.9
